include: package:flutter_lints/flutter.yaml

code-style:
  format: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    avoid_print: true
    prefer_single_quotes: true
    always_declare_return_types: true
    always_put_required_named_parameters_first: true
    prefer_relative_imports: true
    prefer_interpolation_to_compose_strings: true
    directives_ordering: true



